### ISSUE TITLE
Mobile: View and insert comments

### ISSUE THREAD

**Issue by pedropintosilva** [CollaboraOnline/online#1403]
[1. View comments: Add Insert top action within wizard's title bar](#user-content-view-comments)
- [x] Add insert button to the title bar `M:` #1680 ; `co-6-4:` #1703 218fa18b1b0175b945c69b3a2e4c22c58d5d845e

[2. No comments](#user-content-no-comments)
- [x] Create empty state in mobilewizard logic. `M:` #1676 ; `co-6-4:` #1703 : 374f5beb52f712c636ac687c72d2c015c0da8676
- [x] Create empty state structure and style. `M:` #1680 ; `co-6-4:` #1703 245ecd4787eca32e0a898af1edb4741d17316dc5
- [x] Add button into the empty state to insert comment (op) `M:` #1680 ; `co-6-4:` #1703 245ecd4787eca32e0a898af1edb4741d17316dc5
  - [x] Make `Insert Comment` functional `M:` #1680 ; `co-6-4:` #1703 218fa18b1b0175b945c69b3a2e4c22c58d5d845e

[3. Additional actions](#user-content-additional-actions)
- 3 dots menu (kebab menu): 
  - [x] For now increase sizes and improve style.  `M:` #1682 ; `co-6-4:` #1682
  - [ ] In the future maybe having it in a different view
- Is it possible to have `comment` in context menu? (as it happens in core) @lpranam 
  - White list it in online and see if it works on mobile and non-mobile
 - Improve thread view
   - [x] `M:`  #947 ;
   - [x] `co-6-4:` #1711 
 
[4. Testing and UI improvement](#user-content-testing-n-ui)
- [x] Test this out in multiple devices (different sizes)
- [ ]  Test with multiple users

Improve the ongoing work (on master from @lpranam @Rash419  @pedropintosilva) on commenting and view comments on mobile:
* View top level comments
  * View Replies 
* Insert new comment
* Reply to comment
<h2 id="view-comments">1. View comments: Add Insert top action within wizard's title bar</h2> 
When tapping in the the icon to view comments we should also provide an easy to insert a comment right from that panel by adding a text button to that wizard title bar
note: currently we force the user to close the wizard; tap the insert icon; finally insert comment

<h2 id="no-comments">2. No comments</h2>
We should account for this situation and offer a proper empty state instead of just displaying a blank wizard.

* The if condition is in `loleaflet/src/control/Control.JSDialogBuilder.js` root comment
* What should the empty state be?
  * Empty state can be as simple as setting a different background to the whole wizard (e.g.: some icon illustrating that there is currently 0 comments)
  * Or we can have an empty-state card (that actually leverages the existent card element)
    * Showing the user that more cards will be there
    * And working as a big button, triggering `insert comment` (of course  it does not replace the titlebar's insert button described in [1.](#user-content-view-comments) )

<h2 id="additional-actions">3. Additional actions</h2>

* The 3 dots button should open a full blown mobile-friendly view instead of a small drop-down
* The new view should open without without closing its parent (re-use what we are already doing in impress, opening master slide)

<h2 id="testing-n-ui">4. Testing and UI improvement</h2>

* Be sure that we test this out in multiple places
* With multiple users
* Improve UI and add missing states
